// packages/demo/orchestrated/frontend-svelte/src/lib/OrderTable.svelte
<script>
  import Table from './table/Table.svelte';
  import Tbody from './table/Tbody.svelte';
  import Td from './table/Td.svelte';
  import Th from './table/Th.svelte';
  import Thead from './table/Thead.svelte';
  import Tr from './table/Tr.svelte';
  import Working from './Working.svelte';

  export let store;
</script>

{#if !$store || $store.isEmpty}
  <Working />
{:else}
  <Table>
    <Thead>
      <Tr>
        <Th>Id</Th>
        <Th>Text</Th>
        <Th>Value</Th>
        <Th>Customer</Th>
        <Th>USD Info</Th>
      </Tr>
    </Thead>
    <Tbody>
      {#each $store.data as row}
        <Tr>
          <Td>{row.id}</Td>
          <Td>{row.text}</Td>
          <Td>{row.value}</Td>
          <Td>{row.customerName}</Td>
          <Td>{JSON.stringify(row.usdInfo, null, 2)}</Td>
        </Tr>
      {/each}
    </Tbody>
  </Table>
{/if}

// packages/demo/orchestrated/frontend-react/src/components/OrderTable.jsx
import React from 'react';
import { Table, Tbody, Td, Th, Thead, Tr } from './Table';
import { Working } from './Working';

const CustomerTable = ({ data }) => {
  return data ? (
    <Table>
      <Thead>
        <Tr>
          <Th>Id</Th>
          <Th>Text</Th>
          <Th>Value</Th>
          <Th>Customer</Th>
          <Th>USD Info</Th>
        </Tr>
      </Thead>
      <Tbody>
        {data.map(row => (
          <Tr key={row.id}>
            <Td>{row.id}</Td>
            <Td>{row.text}</Td>
            <Td>{row.value}</Td>
            <Td>{row.customerName}</Td>
            <Td>{JSON.stringify(row.usdInfo, null, 2)}</Td>
          </Tr>
        ))}
      </Tbody>
    </Table>
  ) : (
    <Working />
  );
};

export default React.memo(CustomerTable);
